version: '3'

services:

  zipkin:
    container_name: zipkin
    hostname: zipkin
    restart: always
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411 

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    hostname: otel-collector
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8888:8888   
      - 8889:8889   
      - 4317:4317  

  service-a:
    build: 
      dockerfile: ./service-a/dockerfile
    restart: always
    ports:
      - 8080:8080

  service-b:
    build: 
      dockerfile: ./service-b/dockerfile
    restart: always
    ports:
      - 8081:8081
