FROM golang:latest AS builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags "-w -s" -o server ./service-a/cmd

FROM scratch
COPY --from=builder /app/server .
COPY --from=builder /app/service-a/cmd/.env .
CMD ["./server"]